# i18n-tasks works on itself! this is the internal config

# This is not the default config for new apps, but is the internal config for i18n-tasks to analyze itself.
# You can find the default config here: https://github.com/glebm/i18n-tasks/blob/master/templates/config/i18n-tasks.yml

base_locale: en
internal_locale: en

data:
  read:
    - config/locales/%{locale}.yml
  write:
    - config/locales/%{locale}.yml
  yaml:
    write:
      ## do not wrap lines at 80 characters (override default)
      line_width: 96

# Find translate calls
search:
  paths:
    - lib/
  exclude:
    - 'tmp/*'

ignore_missing:
  - i18n.plural.keys
